import type { Task } from './taskTypes';

// Helper to get relative time
const now = Date.now();
const minute = 60 * 1000;
const hour = 60 * minute;
const day = 24 * hour;

// Initial mock tasks
export const initialMockTasks: Task[] = [
  // Open tasks
  {
    id: '1',
    title: 'Borrow 45W USB-C charger',
    shortDescription: 'Need a 45W USB-C charger near Butler',
    category: 'campus',
    credits: 30,
    location: 'Butler Library',
    durationMinutes: 30,
    status: 'open',
    isVerified: true,
    isOnline: false,
    urgency: 'urgent',
    createdAt: new Date(now - 40 * minute).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['butler', 'charger'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '2',
    title: 'Buy a Lunch',
    shortDescription: 'Grab lunch from Ferris Booth Commons',
    category: 'daily',
    credits: 10,
    location: 'Ferris Booth Commons',
    durationMinutes: 20,
    status: 'open',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 3 * hour).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['lunch'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '3',
    title: 'Flyer distribution',
    shortDescription: 'Distribute 50 flyers on campus',
    category: 'daily',
    credits: 20,
    location: 'College Walk',
    durationMinutes: 50,
    status: 'open',
    isVerified: true,
    isOnline: false,
    urgency: 'flexible',
    createdAt: new Date(now - 6 * hour).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['flyer'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '4',
    title: 'Dorm recycling help',
    shortDescription: 'Help carry recycling bags',
    category: 'daily',
    credits: 12,
    location: 'John Jay Hall',
    durationMinutes: 25,
    status: 'open',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 26 * hour).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['recycling'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '5',
    title: 'Study notes sharing',
    shortDescription: 'Share notes for Econ midterm',
    category: 'academic',
    credits: 16,
    location: 'Online',
    durationMinutes: 20,
    status: 'open',
    isVerified: true,
    isOnline: true,
    urgency: 'flexible',
    createdAt: new Date(now - 12 * hour).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['study'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  // Claimed tasks
  {
    id: '6',
    title: 'Help pick a package',
    shortDescription: 'Pick a package from package center',
    category: 'campus',
    credits: 15,
    location: 'Package Center',
    durationMinutes: 15,
    status: 'claimed',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 5 * hour).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['package'],
    claimedByUid: 'mock-user-2',
    claimedAt: new Date(now - 4 * hour).toISOString(),
    completedAt: null,
  },
  {
    id: '7',
    title: 'Printer setup',
    shortDescription: 'Help fix dorm printer',
    category: 'academic',
    credits: 18,
    location: 'Mudd Building',
    durationMinutes: 30,
    status: 'claimed',
    isVerified: true,
    isOnline: false,
    urgency: 'urgent',
    createdAt: new Date(now - 1 * day).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['printer'],
    claimedByUid: 'mock-user-6',
    claimedAt: new Date(now - 20 * hour).toISOString(),
    completedAt: null,
  },
  // Completed tasks
  {
    id: '8',
    title: 'Share class notes',
    shortDescription: 'Send EE class notes PDF',
    category: 'academic',
    credits: 12,
    location: 'Online',
    durationMinutes: 10,
    status: 'completed',
    isVerified: true,
    isOnline: true,
    urgency: 'flexible',
    createdAt: new Date(now - 3 * day).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['notes'],
    claimedByUid: 'mock-user-2',
    claimedAt: new Date(now - 2 * day).toISOString(),
    completedAt: new Date(now - 1 * day).toISOString(),
  },
  {
    id: '9',
    title: 'Bike tire pump',
    shortDescription: 'Help pump bike tires',
    category: 'campus',
    credits: 8,
    location: 'College Walk',
    durationMinutes: 10,
    status: 'completed',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 5 * day).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['bike'],
    claimedByUid: 'mock-user-5',
    claimedAt: new Date(now - 4 * day).toISOString(),
    completedAt: new Date(now - 2 * day).toISOString(),
  },
  // Cancelled task
  {
    id: '10',
    title: 'Move small shelf',
    shortDescription: 'Need to move a small shelf',
    category: 'daily',
    credits: 25,
    location: 'East Campus',
    durationMinutes: 25,
    status: 'cancelled',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 4 * day).toISOString(),
    createdByUid: 'mock-user-1',
    publisherEmail: 'jordan@columbia.edu',
    tags: ['moving'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  // Tasks from other users
  {
    id: '11',
    title: 'Language exchange',
    shortDescription: '30-min English/Chinese exchange',
    category: 'other',
    credits: 18,
    location: 'Butler Library',
    durationMinutes: 30,
    status: 'open',
    isVerified: true,
    isOnline: false,
    urgency: 'flexible',
    createdAt: new Date(now - 70 * minute).toISOString(),
    createdByUid: 'mock-user-2',
    publisherEmail: 'li.andy@columbia.edu',
    tags: ['language'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '12',
    title: 'Math study buddy',
    shortDescription: 'Calc III problem review',
    category: 'academic',
    credits: 22,
    location: 'Mudd Building',
    durationMinutes: 45,
    status: 'open',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 8 * hour).toISOString(),
    createdByUid: 'mock-user-2',
    publisherEmail: 'li.andy@columbia.edu',
    tags: ['math'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '13',
    title: 'Buy a drink',
    shortDescription: 'Grab a coffee from Blue Java',
    category: 'daily',
    credits: 5,
    location: 'Blue Java',
    durationMinutes: 10,
    status: 'claimed',
    isVerified: true,
    isOnline: false,
    urgency: 'normal',
    createdAt: new Date(now - 6 * hour).toISOString(),
    createdByUid: 'mock-user-2',
    publisherEmail: 'li.andy@columbia.edu',
    tags: ['coffee'],
    claimedByUid: 'mock-user-1',
    claimedAt: new Date(now - 5 * hour).toISOString(),
    completedAt: null,
  },
  {
    id: '14',
    title: 'Event photography',
    shortDescription: 'Take photos at club event',
    category: 'other',
    credits: 60,
    location: 'Low Steps',
    durationMinutes: 90,
    status: 'open',
    isVerified: false,
    isOnline: false,
    urgency: 'urgent',
    createdAt: new Date(now - 2 * hour).toISOString(),
    createdByUid: 'mock-user-4',
    publisherEmail: 'pat.singh@columbia.edu',
    tags: ['photo'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
  {
    id: '15',
    title: 'CS project pairing',
    shortDescription: 'Pair program for 1 hour',
    category: 'academic',
    credits: 32,
    location: 'Online',
    durationMinutes: 60,
    status: 'open',
    isVerified: true,
    isOnline: true,
    urgency: 'normal',
    createdAt: new Date(now - 10 * hour).toISOString(),
    createdByUid: 'mock-user-5',
    publisherEmail: 'alex.taylor@columbia.edu',
    tags: ['pair-program'],
    claimedByUid: null,
    claimedAt: null,
    completedAt: null,
  },
];

